name = "release-tracker3"
main = ".output/server/index.mjs"
compatibility_date = "2024-09-19"

[assets]
directory = ".output/public"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

